version: '3.4'

services:
 
  pub-microservice:
    image: ${DOCKER_REGISTRY-}publisher
    build:
      context: .
      dockerfile: PubSubDarpSample.Publisher/Dockerfile
    stdin_open: true
    tty: true

  pub-microservice-dapr:
    image: "daprio/daprd:1.7.0"
    network_mode: "service:pub-microservice"
    depends_on:
      - pub-microservice

  sub-microservice:
    image: ${DOCKER_REGISTRY-}subscriptor
    build:
      context: .
      dockerfile: PubSubDarpSample.Subscriptor/Dockerfile
    stdin_open: true
    tty: true

  sub-microservice-dapr:
    image: "daprio/daprd:1.7.0"
    network_mode: "service:sub-microservice"
    depends_on:
      - sub-microservice